server:
  port: 3002
spring:
  swagger:
    basePackage: cn.myjszl.order.boot.controller
    author:
      name: 不才陈某
      email: xxxx@qq.com
      url: http://chenjiabing666.github.io
    apiInfo:
      title: 订单模块
      description: 订单相关的接口
      version: 1.0
      termsOfServiceUrl: http://ip:${server.port}/${spring.application.name}
      license: license
      licenseUrl: licenseUrl