server:
  port: 9006
spring:
  application:
    ## 指定服务名称，在nacos中的名字
    name: openFeign-consumer
  cloud:
    nacos:
      discovery:
        # nacos的服务地址，nacos-server中IP地址:端口号
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        ## yml文件中存在特殊字符，必须用单引号包含，否则启动报错
        include: '*'
feign:
  ## 开启sentinel的熔断降级
  sentinel:
    enabled: true
  client:
    httpclient:
      # 开启 Http Client
      enabled: true
    config:
      ## default 设置的全局超时时间，指定服务名称可以设置单个服务的超时时间
      default:
        connectTimeout: 5000
        readTimeout: 5000
      openFeign-payment-provider:
        connectTimeout: 30000
        readTimeout: 30000
  ## 开启压缩
  compression:
    request:
      enabled: true
      ## 开启压缩的阈值，单位字节，默认2048，即是2k
      min-request-size: 10
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: true


logging:
  level:
    ## cn.myjszl.service这里是包名，也可以配置特定的openFeign接口
    cn.myjszl.service: debug


#        loggerLevel: full
#        errorDecoder: com.example.SimpleErrorDecoder
#        retryer: com.example.SimpleRetryer
#        defaultQueryParameters:
#          query: queryValue
#          defaultRequestHeaders:
#            header: headerValue
#          requestInterceptors:
#            - com.example.FooRequestInterceptor
#            - com.example.BarRequestInterceptor
#          decode404: false
#          encoder: com.example.SimpleEncoder
#          decoder: com.example.SimpleDecoder
#          contract: com.example.SimpleContract
#ribbon:
#  # 值的是建立链接所用的时间，适用于网络状况正常的情况下， 两端链接所用的时间
#  ReadTimeout: 5000
#  # 指的是建立链接后从服务器读取可用资源所用的时间
#  ConectTimeout: 5000